name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t mynodeapp:latest .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy container
      run: |
        docker stop mynodeapp_container || true
        docker rm mynodeapp_container || true
        docker run -d -p 8081:3000 --name mynodeapp_container mynodeapp:latest
