name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        node-version: '16'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        node-version: '16'

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        node-version: '16'

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: mark00420/mark420:latest
        node-version: '16'

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
    - name: Deploy container
      run: |
        docker stop mynodeapp_container || true
        docker rm mynodeapp_container || true
        docker run -d -p 8081:3000 --name mynodeapp_container mark00420/mark420:latest
